version: '3'
services:
  web:
    build: .
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - wiki

  db:
    image: postgres:latest
    container_name: db
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: wiki
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pg_pass
    networks:
      - wiki

networks:
  wiki:
    driver: bridge