apiVersion: batch/v1
kind: Job
metadata:
  name: web-migrate
spec:
  template:
    spec:
      containers:
      - name: web
        image: my-django-app
        imagePullPolicy: IfNotPresent
        command: ["python", "manage.py", "migrate"]
      restartPolicy: Never
