# Generated by Django 4.2.1 on 2023-08-31 05:33

from django.db import migrations


def create_view(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    migrations.RunSQL(
        """
        CREATE OR REPLACE VIEW RecommendedPages AS
        SELECT page, SUM(rate) as final_rate
        FROM CandidatePages
        WHERE page NOT IN (SELECT page FROM CrawledPages)
        GROUP BY page
        ORDER BY final_rate DESC
        """
    )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_view),
    ]
